### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by Y-Dragon1024** [xuzf-git/CCKS2020-EntityLink#1]
您好，我在学习这个项目 想问下您这个问题改如何处理？
Prefix dict has been built succesfully.
>>>  [《绿皮书》][托尼·利普]和[唐博士]，配上这首[歌]，网友：这种[情愫]有点嗲
Encode ./data/generated/predict_data.txt: 28it [00:00, 1940.27it/s]
Traceback (most recent call last):
  File ".\main.py", line 113, in <module>
    predict(sentence)
  File ".\main.py", line 82, in predict
    res_line = result[line['text_id']]#"""
KeyError: '1'

**Comment by xuzf-git** [comment]
我的运行环境下没有出现该问题，因此我只能给您一些调试建议：
### 1 数据预处理错误
* 检查 ./data/basic_data/predict.json 是否成功分词，并获取每个 entity mention 的offset
* 检查 ./data/generated/predict_data.txt 是否根据候选实体构造好 pairwise 数据，应如下所示
![image](https://user-images.githubusercontent.com/46861544/122171877-cb956c00-ceb2-11eb-9b78-36dfa232ba2d.png)
* 检查 ./data/generated/predict.csv 是否将词语转换成向量索引
### 2 推理阶段错误 
* 添加result的语句，在下图所示位置
![image](https://user-images.githubusercontent.com/46861544/122172575-786fe900-ceb3-11eb-8cd3-f65bc118b21c.png)
正常情况下，会打印一个以test_id为索引的字典，对应于您的报错信息，test_id可能不是'1'
