### ISSUE TITLE
模型准确率

### ISSUE THREAD

**Issue by nathaniel2020** [xuzf-git/CCKS2020-EntityLink#2]
你好，可以问一下你的模型最终的准确率是多少吗？我在自己电脑上跑了10epoch后，准确率只有26%左右

**Comment by xuzf-git** [comment]
这个项目只是个示例，展示一下处理流程，因为我没有显卡所以模型我没有训练过




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuzf-git/CCKS2020-EntityLink"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 下午3:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xuzf-git/CCKS2020-EntityLink] 模型准确率 (#2)





 
你好，可以问一下你的模型最终的准确率是多少吗？我在自己电脑上跑了10epoch后，准确率只有26%左右

**Comment by nathaniel2020** [comment]
这样呀，好的，那我去学习学习这个完整的处理流程。谢谢你啦！
