### ISSUE TITLE
The dataset

### ISSUE THREAD

**Issue by 444352973** [xuzf-git/CCKS2020-EntityLink#3]
您好，原始的数据集似乎失效了，不知道能否更新一下链接，或者私发444352973@qq.com呢。万分感谢。

**Comment by xuzf-git** [comment]
1. README 里面有百度云的下载链接
2. 这个实体链指的数据集和其他一些NLP任务的数据集被打包成了**千言数据集**，可以访问这个链接查看 [https://github.com/luge-ai/luge-ai/](https://github.com/luge-ai/luge-ai/blob/master/information-extraction/entity_linking.md)
